version: 2
jobs:
  test_centos_clang:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --target test -t tcp-echo-test --build-arg CI=${CI} --build-arg CC=/usr/bin/clang --build-arg CXX=/usr/bin/clang++ .
      - run: ./test.sh
  test_centos_gcc:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --target test -t tcp-echo-test --build-arg CI=${CI} .
      - run: ./test.sh
  test_ubuntu_gcc:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --target test -t tcp-echo-test --build-arg BASE_IMAGE=ubuntu:16.04 --build-arg CI=${CI} .
      - run: ./test.sh
  test_ubuntu_clang:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build --target test -t tcp-echo-test --build-arg BASE_IMAGE=ubuntu:16.04 --build-arg CI=${CI}  --build-arg CC=/usr/bin/clang --build-arg CXX=/usr/bin/clang++ .
      - run: ./test.sh
  publish:
    docker:
      - image: circleci/python
    steps:
      - checkout
      - setup_remote_docker
      - run: |
          TAG=$(git describe --long | cut -d- -f 1,2 | sed "s/v//g; s/-/./g")
          echo "Building with tag (${TAG})"
          docker build -t awiddersheim/tcp-echo:${TAG} .
          docker tag awiddersheim/tcp-echo:${TAG} awiddersheim/tcp-echo:latest
          docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
          docker push awiddersheim/tcp-echo

workflows:
  version: 2
  build:
    jobs:
      - test_centos_clang:
          filters:
            tags:
              only: /^v.*/
      - test_centos_gcc:
          filters:
            tags:
              only: /^v.*/
      - test_ubuntu_clang:
          filters:
            tags:
              only: /^v.*/
      - test_ubuntu_gcc:
          filters:
            tags:
              only: /^v.*/
      - publish:
          requires:
            - test_centos_clang
            - test_centos_gcc
            - test_ubuntu_clang
            - test_ubuntu_gcc
          filters:
            branches:
              only: master
            tags:
              only: /^v.*/
